name: Deploy on Release

on:
  release:
    types: [published]
    branches:
     - next

jobs:
  config:
    name: Branch Details
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello there"